#服务配置
server:
  #端口号
  port: 8085
  #项目名
  servlet:
    context-path: /certSign
  #tomcat配置，最大线程数是100，初始化线程是20,超时时间是5000ms
  tomcat:
    min-spare-threads: 20
    max-threads: 100
  connection-timeout: 5000
spring:
  mvc:
    #扫描static目录下的所有文件，如js、img等
    static-path-pattern: /static/**
  #热部署生效
  devtools:
    restart:
      enabled: true
  #扫描html文件
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
  #开启文件上传限制大小
  servlet:
    multipart:
      max-file-size: 60MB
      max-request-size: 300MB
  # 指定执行环境
  profiles:
#    active: #spring.profiles.active#
# 1.internalTest：公司测试环境；2.huaweiCloudTest：华为云测试环境  3.release：华为云生产环境
    active: internalTest
# mybatis config #
mybatis:
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.shenyue.certSign.model

#日志配置
logging:
  config: classpath:logback.xml
